### ISSUE TITLE
Load balancing loss?

### ISSUE THREAD

**Issue by Aman-Goel1** [lucidrains/mixture-of-experts#10]
Hi lucidrains, thanks for the amzing repository. I was wondering where the load balancing loss was? I recall there being two losses, auxillary loss as well as load balancing loss in the 2017 mixture-of-experts paper.

**Comment by lucidrains** [comment]
@Aman-Goel1 hey Aman, as far as I know, the load balancing loss is a auxiliary loss, and is defined [here](https://github.com/lucidrains/mixture-of-experts/blob/master/mixture_of_experts/mixture_of_experts.py#L160-L166)

if you are carrying out new research, recommend using [ST-MoE](https://github.com/lucidrains/st-moe-pytorch), which is more complete and up to date. it contains a new router z-loss that helps a lot with stability

**Comment by Aman-Goel1** [comment]
@lucidrains Thanks for the swift response. I thought this was the implementation of 2017 Shazeer et al.'s MoE but it's GShard's MoE. That was a confusion on my part.

Also thanks for the ST-MoE repository, I'll be most probably using that instead!
