### ISSUE TITLE
implicit inplace operation '*=' cause an error when deriving the back gradient in pytorch

### ISSUE THREAD

**Issue by VRCMF** [lucidrains/mixture-of-experts#6]
In the code [Error](https://github.com/lucidrains/mixture-of-experts/blob/9628ffd38a823b8cd9b2856c4dbf815b79fdc84c/mixture_of_experts/mixture_of_experts.py#L142), it cause the failure of deriving the back gradient.

Solution:
density_1_proxy = density_1_proxy*equals_one_mask[..., None]

**Comment by lucidrains** [comment]
@VRCMF thanks Wei! https://github.com/lucidrains/mixture-of-experts/commit/04201ee9d1add6913032b3cb75c7b59b289b16de
